"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.
"""

from pathlib import Path
from datetime import timedelta
import os

from dotenv import load_dotenv
import dj_database_url


# -----------------------BASE DIR/ENV---------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env from the project root
load_dotenv(BASE_DIR / ".env")


def env(name, default=None):
    """Get an environment variable."""
    return os.getenv(name, default)


def env_bool(name, default=False):
    """Convert an environment variable to boolean."""
    return env(name, str(default)).lower() in (
        "true",
        "1",
        "yes",
        "on",
    )


# -----------------------SECURITY---------------------------------
SECRET_KEY = env("SECRET_KEY")

if not SECRET_KEY:
    raise RuntimeError("SECRET_KEY is not set in the environment.")


DEBUG = env_bool("DEBUG")


ALLOWED_HOSTS = [
    host.strip()
    for host in env("ALLOWED_HOSTS", "").split(",")
    if host.strip()
]


# -----------------------APPLICATIONS---------------------------------
INSTALLED_APPS = [
    # Django built-in apps
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Third-party apps
    "rest_framework",
    "rest_framework_simplejwt",
    "corsheaders",

    # Local app
    "app",
]

AUTH_USER_MODEL = "app.Users"


# -----------------------MIDDLEWARE---------------------------------
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",

    # CORS
    "corsheaders.middleware.CorsMiddleware",

    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


# -----------------------URL CONFIG---------------------------------
ROOT_URLCONF = "config.urls"


# -----------------------TEMPLATES---------------------------------
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


# -----------------------WSGI/ASGI---------------------------------
WSGI_APPLICATION = "config.wsgi.application"

ASGI_APPLICATION = "config.asgi.application"


# -----------------------DATABASE URL---------------------------------
DATABASE_URL = env("DATABASE_URL")

if not DATABASE_URL:
    raise RuntimeError("DATABASE_URL is not set in the environment.")


DATABASES = {
    "default": dj_database_url.parse(
        DATABASE_URL,
        conn_max_age=600,
    )
}


# -----------------------PASSWORD VALIDATION---------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "UserAttributeSimilarityValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "MinimumLengthValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "CommonPasswordValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "NumericPasswordValidator"
        ),
    },
]

# -----------------------INTERNATIONALIZATION---------------------------------
LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# -----------------------STATIC FILES---------------------------------
STATIC_URL = "static/"

# -----------------------DEFAULT PRIMARY KEY---------------------------------
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# -----------------------DJANGO REST FRAMEWORK---------------------------------
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),

    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.AllowAny",
    ),

    "DEFAULT_RENDERER_CLASSES": (
        "rest_framework.renderers.JSONRenderer",
    ),
}


# -----------------------JWT---------------------------------
JWT_SECRET_KEY = env("JWT_SECRET_KEY")

if not JWT_SECRET_KEY:
    raise RuntimeError("JWT_SECRET_KEY is not set in the environment.")


SIMPLE_JWT = {
    # Access token expires after 15 minutes
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),

    # Refresh token expires after 30 days
    "REFRESH_TOKEN_LIFETIME": timedelta(days=30),

    "ROTATE_REFRESH_TOKENS": False,

    "BLACKLIST_AFTER_ROTATION": False,

    "UPDATE_LAST_LOGIN": False,

    "ALGORITHM": "HS256",

    "SIGNING_KEY": JWT_SECRET_KEY,

    "AUTH_HEADER_TYPES": (
        "Bearer",
    ),
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
}

# -----------------------REFRESH TOKEN COOKIE(http-only cookie)---------------------------------
REFRESH_COOKIE_NAME = env(
    "REFRESH_COOKIE_NAME",
    "refresh_token",
)

REFRESH_COOKIE_MAX_AGE = int(
    env(
        "REFRESH_COOKIE_MAX_AGE",
        60 * 60 * 24 * 30,
    )
)

REFRESH_COOKIE_SECURE = env(
    "REFRESH_COOKIE_SECURE",
    "False",
).lower() == "true"

REFRESH_COOKIE_HTTP_ONLY = True

REFRESH_COOKIE_SAMESITE = env(
    "REFRESH_COOKIE_SAMESITE",
    "Lax",
)


# --------------------------GOOGLE OAUTH--------------------------
GOOGLE_CLIENT_ID = env("GOOGLE_CLIENT_ID")


# -----------------------FRONTEND---------------------------------
FRONTEND_ENDPOINT_URL = env("FRONTEND_ENDPOINT_URL")

if not FRONTEND_ENDPOINT_URL:
    raise RuntimeError(
        "FRONTEND_ENDPOINT_URL is not set in the environment."
    )


# -----------------------CORS---------------------------------
CORS_ALLOWED_ORIGINS = [
    origin.strip()
    for origin in env("CORS_ALLOWED_ORIGINS", "").split(",")
    if origin.strip()
]

CORS_ALLOW_CREDENTIALS = True

# -----------------------CSRF---------------------------------
CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in env("CSRF_TRUSTED_ORIGINS", "").split(",")
    if origin.strip()
]


#-------------------------STRIPE CONFIG-------------------------
STRIPE_SECRET_KEY = env("STRIPE_SECRET_KEY")
STRIPE_WEBHOOK_SECRET = env("STRIPE_WEBHOOK_SECRET")
STRIPE_SUCCESS_URL = env("STRIPE_SUCCESS_URL")
STRIPE_CANCEL_URL = env("STRIPE_CANCEL_URL")


# -----------------------EMAIL---------------------------------
EMAIL_BACKEND = env(
    "EMAIL_BACKEND",
    "django.core.mail.backends.console.EmailBackend",
)
