# Generated by Django 6.1 on 2026-08-10 19:25

import app.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.CharField(default=app.models.generate_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_price', models.FloatField(default=0.0)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('street', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=30, null=True)),
                ('country', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='SpareParts',
            fields=[
                ('id', models.CharField(default=app.models.generate_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=255)),
                ('vehicle_type', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=255)),
                ('colour', models.CharField(blank=True, max_length=100, null=True)),
                ('buying_price', models.FloatField()),
                ('marked_price', models.FloatField()),
                ('discount_amount', models.FloatField(default=0.0)),
                ('discount_percentage', models.FloatField(default=0.0)),
                ('image', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('average_rating', models.FloatField(default=0.0)),
                ('total_reviews', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'spareparts',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.CharField(default=app.models.generate_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('role', models.CharField(default='buyer', max_length=30)),
                ('email_verified', models.BooleanField(default=False)),
                ('email_otp_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('email_otp_expires', models.DateTimeField(blank=True, null=True)),
                ('otp_last_sent', models.DateTimeField(blank=True, null=True)),
                ('otp_resend_count', models.IntegerField(default=0)),
                ('otp_attempts', models.IntegerField(default=0)),
                ('otp_locked_until', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.CharField(default=app.models.generate_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=1)),
                ('unit_price', models.FloatField()),
                ('subtotal', models.FloatField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='app.orders')),
                ('sparepart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='app.spareparts')),
            ],
            options={
                'db_table': 'order_items',
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.CharField(default=app.models.generate_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('comment', models.TextField(blank=True, null=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_likes', models.IntegerField(default=0)),
                ('total_dislikes', models.IntegerField(default=0)),
                ('sparepart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='app.spareparts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='app.users')),
            ],
            options={
                'db_table': 'reviews',
            },
        ),
        migrations.CreateModel(
            name='ReviewReactions',
            fields=[
                ('id', models.CharField(default=app.models.generate_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('is_like', models.BooleanField()),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='app.reviews')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='app.users')),
            ],
            options={
                'db_table': 'review_reactions',
            },
        ),
        migrations.AddField(
            model_name='orders',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='app.users'),
        ),
    ]
