# Generated by Django 6.1 on 2026-08-18 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_users_groups_users_is_active_users_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='total_dislikes',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='total_likes',
        ),
        migrations.AddConstraint(
            model_name='reviewreactions',
            constraint=models.UniqueConstraint(fields=('user', 'review'), name='unique_user_review_reaction'),
        ),
    ]
