# Generated by Django 6.1 on 2026-08-19 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_reviews_total_dislikes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='change_password_otp_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='change_password_otp_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='delete_account_otp_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='delete_account_otp_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
