# Generated by Django 6.1 on 2026-08-20 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_users_change_password_otp_expires_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='auth_provider',
            field=models.CharField(choices=[('local', 'Local'), ('google', 'Google')], default='local', max_length=20),
        ),
        migrations.AddField(
            model_name='users',
            name='google_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
